import express from "express";
import expressAsyncHandler from "express-async-handler";

import bcrypt from "bcryptjs";
import data from "../data.js";
import { generateToken, isAdmin, isAuth } from "../utils.js";
import User from "../models/userModel.js";

const userRouter = express.Router();

userRouter.get(
  // we need to get list of topsellers from backend so the final path is /api/users/top-sellers.
  //  a search is done on the users table for only sellers, then each is sorted by their ratings in a descending order.
  //  then limit the amount of top-sellers by 3
  "/top-sellers",
  expressAsyncHandler(async (req, res) => {
    const topsellers = await User.find({ isSeller: true })
      .sort({ "seller.rating": - 1 })
      // .limit();
    res.send(topsellers);
  })
);

userRouter.get(
  "/seed",
  expressAsyncHandler(async (req, res) => {
    //await User.removed({});
    const createdUsers = await User.insertMany(data.users);
    res.send({ createdUsers });
  })
);

//first create sign in router
//post http aware is used because when you are returning singin data,
//a token is generated to authenticate user for next request and when you
//are creating a new resource you need to set your http aware as a post request
//because you cannot run this request through the browser, address bar
//then type it and press enter. You need to use postman to test it.
userRouter.post(
  "/signin",
  expressAsyncHandler(async (req, res) => {
    //An ajax request is sent  to check the user and email in the database
    const user = await User.findOne({ email: req.body.email });
    //you need to check if user exist and compare it with the password
    if (user) {
      if (bcrypt.compareSync(req.body.password, user.password)) {
        //if the comparison is true then i would send only parts of user data
        res.send({
          _id: user._id,
          name: user.name,
          email: user.email,
          isAdmin: user.isAdmin,
          isSeller: user.isSeller,
          //the token would be generated by json webtoken to be used to authenticate and authorise user.
          token: generateToken(user),
        });
        return;
      }
    }
    // if user does not exist or password does not match a status 401 would be sent, which means invalid code.
    res.status(401).send({ message: "Invalid email or password" });
  })
);

userRouter.post(
  "/register",
  expressAsyncHandler(async (req, res) => {
    const user = new User({
      name: req.body.name,
      email: req.body.email,
      password: bcrypt.hashSync(req.body.password, 8),
    });

    const createdUser = await user.save();
    res.send({
      _id: createdUser._id,
      name: createdUser.name,
      email: createdUser.email,
      isAdmin: createdUser.isAdmin,
      isSeller: user.isSeller,
      //the token would be generated by json webtoken to be used to authenticate and authorise user.
      token: generateToken(createdUser),
    });
  })
);

//getting user details for profile screen
userRouter.get(
  "/:id",
  expressAsyncHandler(async (req, res) => {
    const user = await User.findById(req.params.id);
    if (user) {
      res.send(user);
    } else {
      res.send(404).send({ message: "User not Found" });
    }
  })
);

//updates the user profile
userRouter.put(
  "/profile",
  isAuth,
  expressAsyncHandler(async (req, res) => {
    const user = await User.findById(req.user._id);
    if (user) {
      user.name = req.body.name || user.name;
      user.email = req.body.email || user.email;
      if (user.isSeller) {
        user.seller.name = req.body.sellerName || user.seller.name;
        user.seller.logo = req.body.sellerLogo || user.seller.logo;
        user.seller.description =
          req.body.sellerDescription || user.seller.description;
      }
      if (req.body.password) {
        user.password = bcrypt.hashSync(req.body.password, 8);
      }
      const updatedUser = await user.save();
      res.send({
        _id: updatedUser._id,
        name: updatedUser.name,
        email: updatedUser.email,
        isAdmin: updatedUser.isAdmin,
        isSeller: user.isSeller,
        token: generateToken(updatedUser),
      });
    }
  })
);

userRouter.get(
  "/",
  isAuth,
  isAdmin,
  expressAsyncHandler(async (req, res) => {
    const users = await User.find({});
    res.send(users);
  })
);

//api to delete user
userRouter.delete(
  "/:id",
  isAuth,
  isAdmin,
  expressAsyncHandler(async (req, res) => {
    const user = await User.findById(req.params.id);
    if (user) {
      if (user.email === "admin@example.com") {
        res.status(400).send({ message: "Cannot Delete Admin User" });
        return;
      }
      const deleteUser = await user.remove();
      res.send({ message: "User Deleted", user: deleteUser });
    } else {
      res.status(404).send({ message: "User Not Found" });
    }
  })
);

//api to update user
userRouter.put(
  "/:id",
  isAuth,
  isAdmin,
  expressAsyncHandler(async (req, res) => {
    const user = await User.findById(req.params.id);
    if (user) {
      user.name = req.body.name || user.name;
      user.email = req.body.email || user.email;
      user.isSeller = Boolean(req.body.isSeller);
      user.isAdmin = Boolean(req.body.isAdmin);
      const updatedUser = await user.save();
      res.send({ message: "User Updated", user: updatedUser });
    } else {
      res.status(404).send({ message: "User Not Found" });
    }
  })
);

export default userRouter;
