const data = {
    products: [
        {
            _id: '1',
            name: 'Nike Slim Shirt',
            category: 'Shirts',
            image: '/images/p1.jpg',
            price: 120,
            countInStock: 10,
            brand: 'Nike',
            rating: 5,
            numReviews: 10,
            description: 'High quality product',
        },
        {
            _id: '2',
            name: 'Adidas Slim Shirt',
            category: 'Shirts',
            image: '/images/p2.jpg',
            price: 250,
            countInStock: 0,
            brand: 'Adidas',
            rating: 3.5,
            numReviews: 14,
            description: 'High quality product',
        },
        {
            _id: '3',
            name: 'Lacosta Free Shirt',
            category: 'Shirts',
            image: '/images/p3.jpg',
            price: 400,
            countInStock: 40,
            brand: 'Nike',
            rating: 4.0,
            numReviews: 11,
            description: 'High quality product',
        },
        {
            _id: '4',
            name: 'Nike Slim Pants',
            category: 'Pants',
            image: '/images/p4.jpg',
            price: 20,
            countInStock: 5,
            brand: 'Nike',
            rating: 3.5,
            numReviews: 40,
            description: 'High quality product',
        },
        {
            _id: '5',
            name: 'Puma Slim Pants',
            category: 'Pants',
            image: '/images/p5.jpg',
            price: 100,
            countInStock: 36,
            brand: 'Puma',
            rating: 4.5,
            numReviews: 20,
            description: 'High quality product',
        },
        {
            _id: '6',
            name: 'Fubu Slim Pants',
            category: 'Pants',
            image: '/images/p6.jpg',
            price: 350,
            countInStock: 1,
            brand: 'Fubu',
            rating: 3.5,
            numReviews: 15,
            description: 'High quality product',
        },
    ],
};

export default data;